-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  is_premium boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for saved builds
create table builds (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  build_data jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for builds
alter table builds enable row level security;

create policy "Users can view their own builds."
  on builds for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own builds."
  on builds for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own builds."
  on builds for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own builds."
  on builds for delete
  using ( auth.uid() = user_id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, is_premium)
  values (new.id, new.email, false);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
